// Generated by gencpp from file srv/speech_recognitionRequest.msg
// DO NOT EDIT!


#ifndef SRV_MESSAGE_SPEECH_RECOGNITIONREQUEST_H
#define SRV_MESSAGE_SPEECH_RECOGNITIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv
{
template <class ContainerAllocator>
struct speech_recognitionRequest_
{
  typedef speech_recognitionRequest_<ContainerAllocator> Type;

  speech_recognitionRequest_()
    : WakenUp(0)  {
    }
  speech_recognitionRequest_(const ContainerAllocator& _alloc)
    : WakenUp(0)  {
  (void)_alloc;
    }



   typedef int8_t _WakenUp_type;
  _WakenUp_type WakenUp;





  typedef boost::shared_ptr< ::srv::speech_recognitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv::speech_recognitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct speech_recognitionRequest_

typedef ::srv::speech_recognitionRequest_<std::allocator<void> > speech_recognitionRequest;

typedef boost::shared_ptr< ::srv::speech_recognitionRequest > speech_recognitionRequestPtr;
typedef boost::shared_ptr< ::srv::speech_recognitionRequest const> speech_recognitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv::speech_recognitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv::speech_recognitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv::speech_recognitionRequest_<ContainerAllocator1> & lhs, const ::srv::speech_recognitionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.WakenUp == rhs.WakenUp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv::speech_recognitionRequest_<ContainerAllocator1> & lhs, const ::srv::speech_recognitionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv::speech_recognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv::speech_recognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::speech_recognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::speech_recognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::speech_recognitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::speech_recognitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv::speech_recognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef5adef9740917cec6e8de0887929470";
  }

  static const char* value(const ::srv::speech_recognitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef5adef9740917ceULL;
  static const uint64_t static_value2 = 0xc6e8de0887929470ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv::speech_recognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv/speech_recognitionRequest";
  }

  static const char* value(const ::srv::speech_recognitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv::speech_recognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 WakenUp\n"
;
  }

  static const char* value(const ::srv::speech_recognitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv::speech_recognitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.WakenUp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speech_recognitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv::speech_recognitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv::speech_recognitionRequest_<ContainerAllocator>& v)
  {
    s << indent << "WakenUp: ";
    Printer<int8_t>::stream(s, indent + "  ", v.WakenUp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_MESSAGE_SPEECH_RECOGNITIONREQUEST_H
