// Generated by gencpp from file srv/SpeechRecognitionResponse.msg
// DO NOT EDIT!


#ifndef SRV_MESSAGE_SPEECHRECOGNITIONRESPONSE_H
#define SRV_MESSAGE_SPEECHRECOGNITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv
{
template <class ContainerAllocator>
struct SpeechRecognitionResponse_
{
  typedef SpeechRecognitionResponse_<ContainerAllocator> Type;

  SpeechRecognitionResponse_()
    : SpeechRecogition(false)  {
    }
  SpeechRecognitionResponse_(const ContainerAllocator& _alloc)
    : SpeechRecogition(false)  {
  (void)_alloc;
    }



   typedef uint8_t _SpeechRecogition_type;
  _SpeechRecogition_type SpeechRecogition;





  typedef boost::shared_ptr< ::srv::SpeechRecognitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv::SpeechRecognitionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpeechRecognitionResponse_

typedef ::srv::SpeechRecognitionResponse_<std::allocator<void> > SpeechRecognitionResponse;

typedef boost::shared_ptr< ::srv::SpeechRecognitionResponse > SpeechRecognitionResponsePtr;
typedef boost::shared_ptr< ::srv::SpeechRecognitionResponse const> SpeechRecognitionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv::SpeechRecognitionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv::SpeechRecognitionResponse_<ContainerAllocator1> & lhs, const ::srv::SpeechRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.SpeechRecogition == rhs.SpeechRecogition;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv::SpeechRecognitionResponse_<ContainerAllocator1> & lhs, const ::srv::SpeechRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv::SpeechRecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::SpeechRecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::SpeechRecognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08f2232cd1fa1f37d6d3e69d7c20234a";
  }

  static const char* value(const ::srv::SpeechRecognitionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08f2232cd1fa1f37ULL;
  static const uint64_t static_value2 = 0xd6d3e69d7c20234aULL;
};

template<class ContainerAllocator>
struct DataType< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv/SpeechRecognitionResponse";
  }

  static const char* value(const ::srv::SpeechRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool SpeechRecogition\n"
"\n"
;
  }

  static const char* value(const ::srv::SpeechRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SpeechRecogition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpeechRecognitionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv::SpeechRecognitionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv::SpeechRecognitionResponse_<ContainerAllocator>& v)
  {
    s << indent << "SpeechRecogition: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SpeechRecogition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_MESSAGE_SPEECHRECOGNITIONRESPONSE_H
