// Generated by gencpp from file srv/speech_recognitionResponse.msg
// DO NOT EDIT!


#ifndef SRV_MESSAGE_SPEECH_RECOGNITIONRESPONSE_H
#define SRV_MESSAGE_SPEECH_RECOGNITIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv
{
template <class ContainerAllocator>
struct speech_recognitionResponse_
{
  typedef speech_recognitionResponse_<ContainerAllocator> Type;

  speech_recognitionResponse_()
    : SpeechRecogition(0)  {
    }
  speech_recognitionResponse_(const ContainerAllocator& _alloc)
    : SpeechRecogition(0)  {
  (void)_alloc;
    }



   typedef int8_t _SpeechRecogition_type;
  _SpeechRecogition_type SpeechRecogition;





  typedef boost::shared_ptr< ::srv::speech_recognitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv::speech_recognitionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct speech_recognitionResponse_

typedef ::srv::speech_recognitionResponse_<std::allocator<void> > speech_recognitionResponse;

typedef boost::shared_ptr< ::srv::speech_recognitionResponse > speech_recognitionResponsePtr;
typedef boost::shared_ptr< ::srv::speech_recognitionResponse const> speech_recognitionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv::speech_recognitionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv::speech_recognitionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv::speech_recognitionResponse_<ContainerAllocator1> & lhs, const ::srv::speech_recognitionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.SpeechRecogition == rhs.SpeechRecogition;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv::speech_recognitionResponse_<ContainerAllocator1> & lhs, const ::srv::speech_recognitionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv::speech_recognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv::speech_recognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::speech_recognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv::speech_recognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::speech_recognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv::speech_recognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv::speech_recognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdd8078035b634290176b31b40504008";
  }

  static const char* value(const ::srv::speech_recognitionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdd8078035b63429ULL;
  static const uint64_t static_value2 = 0x0176b31b40504008ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv::speech_recognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv/speech_recognitionResponse";
  }

  static const char* value(const ::srv::speech_recognitionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv::speech_recognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 SpeechRecogition\n"
"\n"
;
  }

  static const char* value(const ::srv::speech_recognitionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv::speech_recognitionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SpeechRecogition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speech_recognitionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv::speech_recognitionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv::speech_recognitionResponse_<ContainerAllocator>& v)
  {
    s << indent << "SpeechRecogition: ";
    Printer<int8_t>::stream(s, indent + "  ", v.SpeechRecogition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_MESSAGE_SPEECH_RECOGNITIONRESPONSE_H
