// Generated by gencpp from file srv/SpeechRecognition.msg
// DO NOT EDIT!


#ifndef SRV_MESSAGE_SPEECHRECOGNITION_H
#define SRV_MESSAGE_SPEECHRECOGNITION_H

#include <ros/service_traits.h>


#include <srv/SpeechRecognitionRequest.h>
#include <srv/SpeechRecognitionResponse.h>


namespace srv
{

struct SpeechRecognition
{

typedef SpeechRecognitionRequest Request;
typedef SpeechRecognitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpeechRecognition
} // namespace srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv::SpeechRecognition > {
  static const char* value()
  {
    return "f0cb90399b5d115dbbf48f3fc50c1e7a";
  }

  static const char* value(const ::srv::SpeechRecognition&) { return value(); }
};

template<>
struct DataType< ::srv::SpeechRecognition > {
  static const char* value()
  {
    return "srv/SpeechRecognition";
  }

  static const char* value(const ::srv::SpeechRecognition&) { return value(); }
};


// service_traits::MD5Sum< ::srv::SpeechRecognitionRequest> should match
// service_traits::MD5Sum< ::srv::SpeechRecognition >
template<>
struct MD5Sum< ::srv::SpeechRecognitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv::SpeechRecognition >::value();
  }
  static const char* value(const ::srv::SpeechRecognitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv::SpeechRecognitionRequest> should match
// service_traits::DataType< ::srv::SpeechRecognition >
template<>
struct DataType< ::srv::SpeechRecognitionRequest>
{
  static const char* value()
  {
    return DataType< ::srv::SpeechRecognition >::value();
  }
  static const char* value(const ::srv::SpeechRecognitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv::SpeechRecognitionResponse> should match
// service_traits::MD5Sum< ::srv::SpeechRecognition >
template<>
struct MD5Sum< ::srv::SpeechRecognitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv::SpeechRecognition >::value();
  }
  static const char* value(const ::srv::SpeechRecognitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv::SpeechRecognitionResponse> should match
// service_traits::DataType< ::srv::SpeechRecognition >
template<>
struct DataType< ::srv::SpeechRecognitionResponse>
{
  static const char* value()
  {
    return DataType< ::srv::SpeechRecognition >::value();
  }
  static const char* value(const ::srv::SpeechRecognitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_MESSAGE_SPEECHRECOGNITION_H
