// Generated by gencpp from file srv/speech_recognition.msg
// DO NOT EDIT!


#ifndef SRV_MESSAGE_SPEECH_RECOGNITION_H
#define SRV_MESSAGE_SPEECH_RECOGNITION_H

#include <ros/service_traits.h>


#include <srv/speech_recognitionRequest.h>
#include <srv/speech_recognitionResponse.h>


namespace srv
{

struct speech_recognition
{

typedef speech_recognitionRequest Request;
typedef speech_recognitionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speech_recognition
} // namespace srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::srv::speech_recognition > {
  static const char* value()
  {
    return "c05feedf1ccb8f1f38dacceac93906b6";
  }

  static const char* value(const ::srv::speech_recognition&) { return value(); }
};

template<>
struct DataType< ::srv::speech_recognition > {
  static const char* value()
  {
    return "srv/speech_recognition";
  }

  static const char* value(const ::srv::speech_recognition&) { return value(); }
};


// service_traits::MD5Sum< ::srv::speech_recognitionRequest> should match
// service_traits::MD5Sum< ::srv::speech_recognition >
template<>
struct MD5Sum< ::srv::speech_recognitionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::srv::speech_recognition >::value();
  }
  static const char* value(const ::srv::speech_recognitionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv::speech_recognitionRequest> should match
// service_traits::DataType< ::srv::speech_recognition >
template<>
struct DataType< ::srv::speech_recognitionRequest>
{
  static const char* value()
  {
    return DataType< ::srv::speech_recognition >::value();
  }
  static const char* value(const ::srv::speech_recognitionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::srv::speech_recognitionResponse> should match
// service_traits::MD5Sum< ::srv::speech_recognition >
template<>
struct MD5Sum< ::srv::speech_recognitionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::srv::speech_recognition >::value();
  }
  static const char* value(const ::srv::speech_recognitionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::srv::speech_recognitionResponse> should match
// service_traits::DataType< ::srv::speech_recognition >
template<>
struct DataType< ::srv::speech_recognitionResponse>
{
  static const char* value()
  {
    return DataType< ::srv::speech_recognition >::value();
  }
  static const char* value(const ::srv::speech_recognitionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SRV_MESSAGE_SPEECH_RECOGNITION_H
